[package]
name = "googletest-predicates"
version = "0.2.0"
edition = "2021"
description = "Provides a function to convert googletest matchers into predicates."
license = "MIT"

[dependencies]
googletest = '0.3'
predicates = '2.1'
