[package]
name = "googletest-predicates"
version = "0.1.0"
edition = "2021"
description = "Provides a function to convert googletest matchers into predicates."
license = "MIT"

[dependencies]
googletest = '0.2'
predicates = '2.1'
